implement varnish operations in base class

diff --git a/varnishadm b/varnishadm
--- a/varnishadm
+++ b/varnishadm
@@ -1,5 +1,11 @@
 #!/bin/bash
 
-echo "this is standard output $*"
+echo "this is standard output"
+echo "args: $*"
+echo "another line"
+echo "yet another line"
 
 echo "this is standard error $*" >&2
+echo "another standard error line" >&2
+
+exit 0
